languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "targetOpsBlackNOBG.webp"
  description = "DevOps Solutions for Growing Startups & Established Enterprises 🚀 "

[author]
  name = "Target Ops"
  image = "targetOpsBlackNOBG-FULL.webp"
  headline = "DevOps Solutions for Growing Startups & Established Enterprises 🚀 "
  bio = "DevOps Solutions for Growing Startups & Established Enterprises 🚀 "
  links = [
    { github = "https://github.com/target-ops" },
    { slack = "https://join.slack.com/t/target-ops/shared_invite/zt-2kxdr9djp-YoQSCoRzARa9psxO8aYoaQ" },
    { patreon = "https://www.patreon.com/target_ops"},
    { dev = "https://app.daily.dev/squads/targetops" },
  ]