name: publish
on:
  push:
    branches: [feature/autopush]
  pull_request:
    branches: [feature/autopush]

env:
  ARTICLE_URL_FILE: ${{ github.workspace }}/article_url.txt

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v2
        id: publish_devto
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'posts/**/*.md'
          branch: feature/autopush
          conventional_commits: true

      - name: Get published URL
        run: echo "${{ steps.publish_devto.outputs }}"

      - name: Send URL to Telegram
        if: success()  # Only send if previous steps were successful
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Replace with your Telegram channel ID
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d "chat_id=${TELEGRAM_CHANNEL_ID}&text=New article published: $(cat $ARTICLE_URL_FILE)"

      - name: Comment on Pull Request
        uses: actions-ecosystem/action-create-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes result:
            ```
            ${{ steps.publish_devto.outputs.result_summary }}
            ```